============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-6.2.4, py-1.11.0, pluggy-0.13.1 -- /home/exec/kittygram_final/backend/venv/bin/python3
django: settings: kittygram_backend.settings (from ini)
rootdir: /home/exec/kittygram_final, configfile: pytest.ini
plugins: django-4.4.0, pythonpath-0.7.3
collecting ... collected 12 items

tests/test_connection.py::test_link_connection[taski_domain] PASSED      [  8%]
tests/test_connection.py::test_link_connection[kittygram_domain] PASSED  [ 16%]
tests/test_connection.py::test_projects_on_same_ip PASSED                [ 25%]
tests/test_connection.py::test_kittygram_static_is_available PASSED      [ 33%]
tests/test_connection.py::test_kittygram_api_available PASSED            [ 41%]
tests/test_dockerhub_images.py::test_dockerhub_images_exist FAILED       [ 50%]
tests/test_files.py::test_infra_files_exist PASSED                       [ 58%]
tests/test_files.py::test_deploy_info_file_content PASSED                [ 66%]
tests/test_files.py::test_backend_dockerfile_exists PASSED               [ 75%]
tests/test_files.py::test_backend_dokerfile_content PASSED               [ 83%]
tests/test_files.py::test_workflow_file FAILED                           [ 91%]
tests/test_files.py::test_requirements_location PASSED                   [100%]

=================================== FAILURES ===================================
_________________________ test_dockerhub_images_exist __________________________

deploy_file_info = (PosixPath('/home/exec/kittygram_final/tests.yml'), 'tests.yml')
deploy_info_file_content = {'dockerhub_username': 'toprihlop', 'kittygram_domain': 'https://thelastone.ddns.net', 'repo_owner': 'TikhomirovRoman', 'taski_domain': 'https://thechosenone.ddns.net'}
dockerhub_username_key = 'dockerhub_username'

    def test_dockerhub_images_exist(
            deploy_file_info: tuple[Path, str],
            deploy_info_file_content: dict[str, str],
            dockerhub_username_key: str
            ) -> None:
        common_part_of_link_to_docker_hub = (
            'https://hub.docker.com/v2/namespaces/{username}/repositories/{image}/'
        )
        expected_docker_images = (
            'kittygram_backend', 'kittygram_frontend', 'kittygram_gateway'
        )
        docker_hub_username = _get_dockerhub_username(
            deploy_file_info, deploy_info_file_content, dockerhub_username_key
        )
        expected_status_code = HTTPStatus.OK
        for image in expected_docker_images:
            link = common_part_of_link_to_docker_hub.format(
                username=docker_hub_username,
                image=image
            )
            response = requests.get(link)
>           assert response.status_code == expected_status_code, (
                '\u0423\u0431\u0435\u0434\u0438\u0442\u0435\u0441\u044c, \u0447\u0442\u043e \u0432 \u0432\u0430\u0448\u0435\u043c DockerHub-\u0430\u043a\u043a\u0430\u0443\u043d\u0442\u0435 \u0434\u043e\u0441\u0442\u0443\u043f\u0435\u043d \u043e\u0431\u0440\u0430\u0437 '
                f'`{image}`. \u041e\u0431\u0440\u0430\u0437 \u0434\u043e\u043b\u0436\u0435\u043d \u0431\u044b\u0442\u044c \u043f\u0443\u0431\u043b\u0438\u0447\u043d\u044b\u043c.'
            )
E           AssertionError: \u0423\u0431\u0435\u0434\u0438\u0442\u0435\u0441\u044c, \u0447\u0442\u043e \u0432 \u0432\u0430\u0448\u0435\u043c DockerHub-\u0430\u043a\u043a\u0430\u0443\u043d\u0442\u0435 \u0434\u043e\u0441\u0442\u0443\u043f\u0435\u043d \u043e\u0431\u0440\u0430\u0437 `kittygram_gateway`. \u041e\u0431\u0440\u0430\u0437 \u0434\u043e\u043b\u0436\u0435\u043d \u0431\u044b\u0442\u044c \u043f\u0443\u0431\u043b\u0438\u0447\u043d\u044b\u043c.
E           assert 404 == <HTTPStatus.OK: 200>
E             +404
E             -<HTTPStatus.OK: 200>

tests/test_dockerhub_images.py:40: AssertionError
______________________________ test_workflow_file ______________________________

base_dir = PosixPath('/home/exec/kittygram_final')
workflow_file_name = 'kittygram_workflow.yml'

    def test_workflow_file(base_dir: Path, workflow_file_name: str):
        path_to_file = base_dir / workflow_file_name
>       assert path_to_file.is_file(), (
            f'\u0423\u0431\u0435\u0434\u0438\u0442\u0435\u0441\u044c, \u0447\u0442\u043e \u043a\u043e\u0440\u043d\u0435\u0432\u0430\u044f \u0434\u0438\u0440\u0435\u043a\u0442\u043e\u0440\u0438\u044f \u043f\u0440\u043e\u0435\u043a\u0442\u0430 \u0441\u043e\u0434\u0435\u0440\u0436\u0438\u0442 \u0444\u0430\u0439\u043b '
            f'`{workflow_file_name}`, \u0432 \u043a\u043e\u0442\u043e\u0440\u043e\u043c \u043e\u043f\u0438\u0441\u0430\u043d workflow \u0434\u043b\u044f Kittygram.'
        )
E       AssertionError: \u0423\u0431\u0435\u0434\u0438\u0442\u0435\u0441\u044c, \u0447\u0442\u043e \u043a\u043e\u0440\u043d\u0435\u0432\u0430\u044f \u0434\u0438\u0440\u0435\u043a\u0442\u043e\u0440\u0438\u044f \u043f\u0440\u043e\u0435\u043a\u0442\u0430 \u0441\u043e\u0434\u0435\u0440\u0436\u0438\u0442 \u0444\u0430\u0439\u043b `kittygram_workflow.yml`, \u0432 \u043a\u043e\u0442\u043e\u0440\u043e\u043c \u043e\u043f\u0438\u0441\u0430\u043d workflow \u0434\u043b\u044f Kittygram.
E       assert False
E        +  where False = <bound method Path.is_file of PosixPath('/home/exec/kittygram_final/kittygram_workflow.yml')>()
E        +    where <bound method Path.is_file of PosixPath('/home/exec/kittygram_final/kittygram_workflow.yml')> = PosixPath('/home/exec/kittygram_final/kittygram_workflow.yml').is_file

tests/test_files.py:62: AssertionError
=========================== short test summary info ============================
FAILED tests/test_dockerhub_images.py::test_dockerhub_images_exist - Assertio...
FAILED tests/test_files.py::test_workflow_file - AssertionError: \u0423\u0431\u0435\u0434\u0438\u0442\u0435\u0441\u044c, \u0447...
=================== 2 failed, 10 passed, 1 warning in 6.75s ====================
